### ISSUE TITLE
Ignore Network Interfaces Shows Wrong Context

### ISSUE THREAD

**Issue by kpb** [spring-cloud/spring-cloud-static#7]
Version: Dalston.SR5.

https://cloud.spring.io/spring-cloud-static/Dalston.SR5/single/spring-cloud.html#ignore-network-interfaces

Suggests using application.yml to set network whitelist:
```
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
```
This doesn't work for me. The inetutils settings must be done in the `bootstrap` context (ENV var, java system property, or bootstrap.yml), not the application context.
